version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  development:
      build-development:
        commands:
          - npm run build-development

      artifacts:
          files:
            - '**/*'
          discard-paths: no
          base-directory: build
  production:
      build:
        commands:
            - npm run build

      artifacts:
          files:
            - '**/*'
          discard-paths: no
          base-directory: build